### PR TITLE
Updates for 2.11.0-M8.

### PR DESCRIPTION
**Pull request by paulp**
Removed unnecessary test-time dependency on xml.

Eliminated a bunch of unused expression warnings.

### CODE REVIEW

**Comment by 0xRoch** [comment]
@paulp thanks !

**Comment by 0xRoch** [comment]
@paulp please do not hesitate if you need me to do a release on central. (the snapshots have been updated).

**Comment by paulp** [comment]
Normally I would say it can wait, but the problem right now is that the snapshot version looks older than the release version. So it would be nice to get the snapshot bumped to 0.3.1, and in general to use 3 digit versions.

**Comment by 0xRoch** [comment]
Good point !
I’ll fix it

**Pull request merged**
