### PR TITLE
SBT 0.13 Support

### PR DESCRIPTION
**Pull request by theon**
I had to make this somewhat ugly change to scct for sbt-scct to work with sbt 0.13. `global.settings.outdir.value` returns null with sbt 0.13. Couldn't find anything in the sbt release notes to give a clue as to why this is.

Because this change only effects sbt 0.13, we only need it on `master` and not on the `2.9.2` branch (used for sbt 0.12)

Caveat: I haven't tested this change with a maven project yet, so I don't know what the impact of this change is for maven users.

### CODE REVIEW

**Comment by theon** [comment]
I have a scala project at work that uses gradle, so I can look into testing this change with the gradle plugin.

**Comment by 0xRoch** [comment]
@theon I think its fine but I wanted to fix #4 before I merge it just to make sure it passes the CI build. For some reasons can run the tests in local but not on travis, something to do with the scalaTargetDir in InstrumentationSpec.scala

**Comment by theon** [comment]
I've pushed a change that has got past that problem: just over half the tests are passing now. Now there is a `ConcurrentModificationException` failing the rest of the tests. I'm away from my computer this afternoon, so I pushed what I had.

**Comment by 0xRoch** [comment]
@theon great thank you for helping

**Comment by theon** [comment]
Fix for `ConcurrentModificationException` is here: https://github.com/SCCT/scct/pull/10

**Pull request merged**
