### PR TITLE
adding the number of the statement and number of the covered statement t...

### PR DESCRIPTION
**Pull request by namiazad**

### CODE REVIEW

**Comment by 0xRoch** [comment]
Hi @nasserazad thank you for your pull request your changes should now be available on the last snapshot. Let me know if you need me to publish a release on central.

**Comment by 0xRoch** [comment]
Ok I'll do it tomorrow morning. :+1:

**Comment by namiazad** [comment]
Awesome : )

**Comment by 0xRoch** [comment]
Issue #29

**Pull request merged**
