### PR TITLE
Publish SCCT on Sonatype

### PR DESCRIPTION
**Pull request by 0xRoch**

### CODE REVIEW

**Comment by 0xRoch** [comment]
https://issues.sonatype.org/browse/OSSRH-7346

**Comment by 0xRoch** [comment]
```
<dependency>
  <groupId>com.github.scct</groupId>
  <artifactId>scct_2.10</artifactId>
  <version>0.2-SNAPSHOT</version>
</dependency>
```

**Comment by seratch** [comment]
:+1:

**Comment by theon** [comment]
:+1: Good work sorting out the sonatype repo

**Comment by 0xRoch** [comment]
@theon not quite done yet, I want to make it automatic with Travis CI, something similar to : https://gist.github.com/D-Roch/6729618

**Comment by theon** [comment]
@D-Roch Nice, looks good!

**Pull request merged**
